### PR TITLE
Add eslint and prettier

### PR DESCRIPTION
**Pull request by ryanio**
This PR adds eslint and prettier to Cleftron to ensure a consistent code style, improve code readability and improve the dev experience. See: [Why Prettier?](https://prettier.io/docs/en/why-prettier.html)

I recommend [adding eslint to your favorite editor](https://eslint.org/docs/user-guide/integrations#editors). Prettier will automatically run on precommit, but is also sweet to have [format on save in your editor](https://prettier.io/docs/en/editors.html).

### CODE REVIEW

**Comment by holiman** [comment]
Thanks! Hope it's ok if I cherry-pick the two commits where it's imported. It'll be a bit of a mess to merge my `queue` branch if I merge this PR in first. And then I can run the linter/prettyfier when everything's back to master again.

**Comment by ryanio** [comment]
Yep no problem, you can just run prettier on the files like so: `prettier --write "**/*.{js,vue,json,md}"`

I did do this on your `queue` branch and this PR is to merge into that. Whatever works though! 👍

**Comment by holiman** [comment]
Oh, I see. There was one more commit that made it in, could you please rebase it on top of current master?

**Comment by ryanio** [comment]
Sure I'll create a new PR into master

**Pull request closed without merging**
