### PR TITLE
The app

### LINKED ISSUE #1: Create Electron-based UI
`Clef` was integrated into Geth the other day.

## Background

Main docs is here:
https://github.com/ethereum/go-ethereum/tree/master/cmd/clef

Tutorial:
https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/tutorial.md

Docs about rules:
https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/rules.md

There exists a QT-based UI here: https://github.com/holiman/qtsigner. The QT-based UI is somewhat full-fledged, in that it supports modifying requests in the UI (not just approve/deny). 

There is also a GTK-based UI: https://github.com/holiman/gtksigner (very much work in
progress, I wrote it to be able to run on Qubes-os on a Fedora-based Qube). This is much less advanced. 

### Task

Create a small Electron-based UI, fully bundled with no external components, which starts `clef` under the hood and communicates with the binary process. 

For starters, a minimal UI which can only approve/deny operations is sufficient. The UI should, like the QT-based one, have a system tray icon which is activated when requests come in. The user should be able to click it, see  the provided information about the request, and approve/deny the operation. 

The entire thing should be bundled, and not depend on loading external resources. It should not require having nodejs or npm libraries installed.

### PR DESCRIPTION
**Pull request by StevenJNPearce**
fixes #1

### CODE REVIEW

**Comment by holiman** [comment]
Thanks!

I'm having some problems running/building it: https://gist.github.com/holiman/b900a40f4935cb640a737e4ea7eed986

**Comment by StevenJNPearce** [comment]
@holiman 

Was a typo. I hadn't caught it as windows doesn't care about capitalization in filenames. Fixed, should be working now.

**Comment by holiman** [comment]
Looks good, a few minor things missing. 

When a json rpc request like the one below comes in: 
```
  {"jsonrpc":"2.0","id":5,"method":"ApproveTx","params":[{"transaction":{"from":"0xcf6cd422f9b45778ad8a564edfbf8abab96e363a","to":"0x07a565b7ed7d7a678680a4c162885bedbb695fe0","gas":"0x333","gasPrice":"0x123","value":"0x10","nonce":"0x0","data":"0x4401a6e40000000000000000000000000000000000000000000000000000000000000012","input":null},"call_info":[{"type":"WARNING","message":"Invalid checksum on to-address"},{"type":"Info","message":"safeSend(address: 0x0000000000000000000000000000000000000012)"}],"meta":{"remote":"127.0.0.1:38366","local":"localhost:8550","scheme":"HTTP/1.1"}}]}
```
The extra info is ignored. In this case, there were two messages:

* "type":"WARNING","message":"Invalid checksum on to-address"
* "Info","message":"safeSend(address: 0x0000000000000000000000000000000000000012)"

The presence of those need to generate more items on the approval form. 

Other than that, I think it's good enough to accept.

**Comment by holiman** [comment]
One more: for `ApproveNewAccount` there should be a password-field, so the user can set a password. It should be fairly trivial to add, though, and seeing as how it wasn't documented I don't see that as a blocker.

**Pull request merged**
